Module 3
TheLegendaryPan/git-playground pull request #7
Opened 2020-08-06 20:36 UTC by TheLegendaryPan

New PR for module 3 project

2020-08-19 15:24 UTC, hugh-emerson requested changes
You're getting there but a bit more work is needed on client_test.py.

Additionally, the chromedriver setup needs to be fixed so it works on other people's machines, there is a lot of code that should be deleted, and the README needs updating. See my comments for details.

2020-08-19 15:24 UTC, hugh-emerson commented on .env.test
> +username = 'panyongfeng1@gmail.com'
You shouldn't be committing any real credentials!

New things like this should be mentioned in the README, but actually I think these last 4 can be deleted. See my comment on the selenium test file. 

Also, a minor point: by convention, environment variable names are written like APP_KEY (capitalised and with underscores)

2020-08-19 15:24 UTC, hugh-emerson commented on Test/client_test.py
> +#magically worked...
A lot of these comments should be removed

2020-08-19 15:24 UTC, hugh-emerson commented on trelloapp.py
> +# result_card=Trello()
Unused code should be deleted

2020-08-19 15:24 UTC, hugh-emerson commented on trelloapp.py
> +    def create_board_4_test(self, name):
Don't use abbreviations like this in names. It makes it harder to read, not easier. This should be called "create_board_for_test", or just "create_test_board"

2020-08-19 15:24 UTC, hugh-emerson commented on Test/client_test.py
> +    response = client.get('/items/get_all_cards')
The index page redirects you to /items/get_all_cards, and that looks deliberate. So a test of the index page should be using client.get('/') and then asserting status_code == 302.

You should also assert response.location matches what you expect (the destination of the redirect).

2020-08-19 15:24 UTC, hugh-emerson commented on Test/hello_test.py
> +from hello import app
This file should be deleted

2020-08-19 15:24 UTC, hugh-emerson commented on Test/multiple_test.py
> +import pytest
This file should be deleted.

2020-08-19 15:24 UTC, hugh-emerson commented on Test/debug.log
> +[0725/004226.767:ERROR:process_reader_win.cc(123)] NtOpenThread: {Access Denied} A process has requested access to an object, but has not been granted those access rights. (0xc0000022)
I don't know what generated this file, but it should be deleted. If you keep generating it, add it to the .gitignore

2020-08-19 15:24 UTC, hugh-emerson commented on Test/client_test.py
> +    response = client.get('/items/get_all_cards')
This test is currently ignoring the result of client.get. 
You are calling Trello.get_all_cards_from_board directly and then making assertions on the result of that. (You pass response in as a parameter, but that doesn't do anything. The result would be the same if you called `Trello.get_all_cards_from_board({})`). Your test should be making assertions about the result of going to the /items/get_all_cards page of your web app, i.e. should be asserting things about `response`. Delete the Trello.get_all_cards_from_board line from the test.

E.g. `assert b"Test to do item" in response.data`

But as it's written, this test will fail when you check response.data because of your mocked response. You set `"idList": "67890",` but that doesn't match any of the list ids in .env.test, so when you make the view model, it won't match any of the expected lists, and it won't get included in the index html.

2020-08-19 15:24 UTC, hugh-emerson commented on Test/client_test.py
> +    monkeypatch.setattr(Trello, "get_all_cards_from_board", substitute_trello_api_mock)
What you've written is essentially a unit test of the "app", by mocking out the other class - Trello. But the exercise asks you to try writing an integration test - where we actually check how the app functions as a whole. So instead of mocking `Trello`, `get_all_cards_from_board` could you try mocking `requests`, `request`

2020-08-19 15:24 UTC, hugh-emerson commented on timeconvert.py
> +from datetime import datetime, date, timedelta
This file should be deleted

2020-08-19 15:24 UTC, hugh-emerson commented on trello_class.py
> +class TrelloItem:
The file should be called trello_item to match the class

2020-08-19 15:24 UTC, hugh-emerson commented on trelloapp.py
> +    def get_card_name_and_id(self):
This function is unused and doesn't return anything. 

Even if it did, the print statements should be deleted

2020-08-19 15:24 UTC, hugh-emerson commented on trelloapp.py
> +    def get_list_name_and_id(self):
Also unused

2020-08-19 15:24 UTC, hugh-emerson commented on Test/selenium_test.py
> +#driver = webdriver.Chrome(r"C:\Users\Feng and Li\Desktop\DevOps\git-playground\DevOps-Course-Starter\drivers\chromedriver.exe")
Delete this line

2020-08-19 15:24 UTC, hugh-emerson commented on Test/selenium_test.py
> +    with webdriver.Chrome(r"C:\Users\Feng and Li\Desktop\DevOps\git-playground\DevOps-Course-Starter\drivers\chromedriver.exe") as driver:
This obviously won't work on my laptop for example.

You can just do `webdriver.Chrome() as driver` and it will work on other people's machines if they have chromedriver.exe on their PATH or in the root of this directory. And you've committed chromedriver.exe to the repo so it should work. 

Ideally, you should avoid committing dependencies like chromedriver - gitignore it and mention in the README that the developer needs Chrome + chromedriver.exe to run the tests

2020-08-19 15:24 UTC, hugh-emerson commented on trelloapp.py
> +    list_id_Done = os.getenv("list_id_Done")
With this setup, you will have to be a bit careful when you want to override it with .env.test. These variables are being set from os.getenv whenever this file is first imported. Loading a new dotenv will not automatically update these.

2020-08-19 15:24 UTC, hugh-emerson commented on Test/selenium_test.py
> +def test_trello(driver):
This test should be deleted. I assume it was just something you were doing to experiment with selenium

2020-08-21 10:57 UTC, TheLegendaryPan commented on trelloapp.py
> +# result_card=Trello()
Thanks Emerson, I'm a bit raw in python and coding so some of these comments help me to quickly understand why certains things were done. Will be more clean as I get more familiar with coding.

2020-08-21 10:59 UTC, TheLegendaryPan commented on .env.test
> +username = 'panyongfeng1@gmail.com'
Thanks. removed! Didnt realise .env.test got published!

2020-08-21 10:59 UTC, TheLegendaryPan commented on Test/client_test.py
> +#magically worked...
Removed some of the comments

2020-08-21 11:30 UTC, TheLegendaryPan commented on trelloapp.py
> +    def create_board_4_test(self, name):
updated the function names. Thanks!

2020-08-21 11:48 UTC, TheLegendaryPan commented on Test/client_test.py
> +    response = client.get('/items/get_all_cards')
thanks. updated the test cases.

2020-08-21 11:49 UTC, TheLegendaryPan commented on Test/selenium_test.py
> +#driver = webdriver.Chrome(r"C:\Users\Feng and Li\Desktop\DevOps\git-playground\DevOps-Course-Starter\drivers\chromedriver.exe")
deleted!

2020-08-21 11:51 UTC, TheLegendaryPan commented on Test/selenium_test.py
> +def test_trello(driver):
removed

2020-08-21 12:10 UTC, TheLegendaryPan commented on Test/selenium_test.py
> +    with webdriver.Chrome(r"C:\Users\Feng and Li\Desktop\DevOps\git-playground\DevOps-Course-Starter\drivers\chromedriver.exe") as driver:
Got it. I put the chromedriver.exe into my python script folder and "with webdriver.Chrome() as driver:" now worked.

2020-08-21 12:11 UTC, merged