module3 update post review
TheLegendaryPan/git-playground pull request #8
Opened 2020-08-21 12:29 UTC by TheLegendaryPan

Hi, I've updated the code and fixed the chrome driver issue as well. I still kept some comments as I'm still very new to coding and they do help me to go through my code. Thanks.

2020-08-24 23:25 UTC, hugh-emerson requested changes
Almost there, can you just try fixing the test overrides for e.g. the `board_id` env variable and also try adding some interaction with the page to the selenium test?

I understand wanting to keep some examples of code around since it's all new to you, but what about hello.py, hello_test.py, multiple_test.py, now that you have proper tests to look at? If they're not helpful anymore, can you delete those files?

2020-08-24 23:25 UTC, hugh-emerson commented on .vscode/settings.json
> +    "python.pythonPath": "c:\\Users\\DevOps-Feng\\AppData\\Local\\Programs\\Python\\Python38-32\\python.exe"
This should be `"python.pythonPath": "env\\Scripts\\python.exe"` - it shouldn't be specific to your computer, and also we want to use the version of python in /env (part of our virtual environment for this project, not your global python installation)

2020-08-24 23:25 UTC, hugh-emerson commented on Test/selenium_test.py
>      os.environ['TRELLO_BOARD_ID'] = board_id
Your test is actually using the real board.

First of all, you're setting TRELLO_BOARD_ID, but TrelloApp.py is doing `board_id= os.getenv("board_id")`

Secondly, TrelloApp is declaring `board_id= os.getenv("board_id")` when the class is defined, not when it is initiated. So, it is setting its value long before you reach this line of the test. Simplest fix would be to move it into an __init__ function, or slightly hackily your test could actually overwrite it directly with `Trello.board_id = board_id` instead of going via os.environ.

2020-08-24 23:25 UTC, hugh-emerson commented on Test/selenium_test.py
>      driver.get('http://localhost:5000/')
Could you try adding some page interaction? You've demonstrated you can do it in the test you wrote for the trello website, but can you do it for your todo app?
At least click the link to create_item_page, add a todo and then check that you are back on the home page and the new item is displayed

2020-08-24 23:25 UTC, hugh-emerson commented on .env.test.test
>  list_id_Pending = '5ef1186d2fd57d026f03add0'
You've accidentally renamed this file to ".env.test.test", so your test isn't using it.

Also, your integration test isn't actually using this file's values for APP_KEY etc anyway, because of a problem I mentioned in another comment - your trelloapp.py file is grabbing values from the environment before your test tries to set the new values for the environment variables. The variables in your Trello class are never updated.

2020-08-30 23:58 UTC, merged

2020-08-31 00:11 UTC, TheLegendaryPan commented on Test/selenium_test.py
>      driver.get('http://localhost:5000/')
Hi, I've added a new test case for selenium to add an item to the to do list, then checked if the page returned to the home page and new item is present. I think I got it right this time. Please review. I've merged this change along with the Vagarant / VM changes for module 4. Thanks again.

2020-08-31 00:12 UTC, TheLegendaryPan commented on Test/selenium_test.py
>      driver.get('http://localhost:5000/')
I've created a new pull request #10 for above.

2020-08-31 23:05 UTC, TheLegendaryPan commented on Test/selenium_test.py
>      driver.get('http://localhost:5000/')
Hi Hugh. I think i got the bit with board_id sorted. I added the board creation as part of Test init file and now the test board gets deleted after creation. Added new test case to add item. I've created another PR (#11) combined with module 4 project. Hopefully this time is good. Thanks again.